### ISSUE TITLE
Assertion `limit` failed utree_distances

### ISSUE THREAD

**Issue by padpadpadpad** [amkozlov/raxml-ng#130]
Hi all

I am using raxml-ng that I installed via conda (RAxML-NG v. 1.0.3) on a ~250bp alignment of 3000 OTUs.

It got quite far and then I got this error when i checked on it this morning.

```raxml-ng: /opt/conda/conda-bld/raxml-ng_1626880669841/work/libs/pll-modules/src/tree/utree_distances.c:790: _cmp_splits: Assertion `limit' failed.
Aborted (core dumped)```

This was after running the command:

```raxml-ng --msa alignment_ps_otu_99percent_filtered.fasta --model GTR+G --seed 2 --prefix raxml/myxo1 --threads 4 --outgroup TCGCTGGCCGAATCGGAAGGTCTGACTCCGCAGGAACTGATCAACGCAAAGCCGGTGGCTGCCGCGATCAAGGAATTCTTCGGATCCTCGCAGCTTTCGCAGTTCATGGACCAGAACAATCCGCTTTCGGAAGTCACCCACAAGCGCCGCGTTTCGGCACTTGGACCAGGTGGCCTGACCCGCGAGCGTGCTGGCTTCGAAGTACGC```

Attached is my alignment and my log file. Any ideas much appreciated.
[log_and_alignment.zip](https://github.com/amkozlov/raxml-ng/files/7482371/log_and_alignment.zip)

**Comment by amkozlov** [comment]
Hi @padpadpadpad,

thanks for reporting! There is a bug when trying to root a collapsed multifurcating tree. So until I fix it, the easiest workaround would to be resume the analysis without `--outgroup` option, and then run a separate `raxml-ng --evaluate --tree myxo1.raxml.bestTree --outgroup X,Y ` if needed.

Side note: apparently, you are trying to infer a "tree of reads", which is generally a bad idea due to insufficient signal (see eg. [this discussion](https://groups.google.com/g/raxml/c/CbbnIZn8DAI/m/ugTT8Z_gBQAJ?utm_medium=email&utm_source=footer)). Please consider using phylogenetic placement instead: https://github.com/Pbdas/epa-ng

Side note 2: please don't use sequences as taxon names, this was *really* inconvenient to work with.

**Comment by amkozlov** [comment]
fixed in [v1.1.0 ](https://github.com/amkozlov/raxml-ng/releases/tag/1.1.0)
