### ISSUE TITLE
Handle near-zero branch lengths? 

### ISSUE THREAD

**Issue by stamatak** [amkozlov/raxml-ng#23]
This was a recurrent issue in RAxML when dataset had so little diversity that the br-len optimization hit the branch length minimum set in the code. Also need to be careful to maybe resolve inner nodes with zero branch lengths into multi-furcations. There were 1-2 papers discussing this.

**Comment by ksw9** [comment]
Hi,
I am fitting trees to unpartitioned alignments with little diversity. I'm wondering if you could advise about the best approach for fitting and interpreting branch lengths. Currently, I fit trees using a JC model and correcting for invariant sites. 

`raxml-ng --all --msa ${fasta} --model ${model}+ASC_STAM{$A_invar/$C_invar/$G_invar/$T_invar}+FU{$a/$c/$g/$t} --prefix ${prefix} --blopt nr_safe --threads $threads
`
-If my alignment is not partitioned, do I need to do a subsequent step following the model fitting and bootstrapping  to optimize branch lengths?
-Should I change the --brlmin parameter to lower than 1e-6 or, instead, after I fit trees, could I set branch lengths inferred to be this minimum 1e-6 length to 0, so that I can visualize where polytomies exist in the fit trees? 

Thanks in advance for your help!
Best,

**Comment by amkozlov** [comment]
@ksw9 could you please re-post your question in our user support google group:
https://groups.google.com/forum/#!forum/raxml 

thanks!

**Comment by ksw9** [comment]
Of course, thanks!

**Comment by lixingguang** [comment]
@is there any good model for traits, thanks.

**Comment by lixingguang** [comment]
@stamatak @amkozlov I am very interesting about using ml method to do traits phylogenetic, is there any good methods for this?

**Comment by amkozlov** [comment]
implemented as of raxml-ng 1.0
