### ISSUE TITLE
Different results from different version

### ISSUE THREAD

**Issue by cynthiawqy** [amkozlov/raxml-ng#50]
Hi
When I set this dataset as the input alignment,  [link](https://github.com/roblanf/BenchmarkAlignments/tree/master/datasets/Worobey_2014c) 
I got different loglikelihood from different versions. The model I used:
PTHREADS: --msa alignment.phy --model GTR+G+F 
MPI: --msa alignment.phy --model GTR+G+F --threads 1
In PTHREADS version, the loglikehood is about -14406, while in MPI version, the loglikelihood is about -14018. I have tested several times but got similar results. I am just wondering why this is happening.
Thanks in advance.

**Comment by amkozlov** [comment]
Could you please try using the same random seed (e.g. `--seed 1`) for both runs and post log files here? Thanks!

**Comment by cynthiawqy** [comment]
Hi Alexey,

I have tested several times and I found that it is not because different versions. Even if I use same input and parameters in the same version, I can still got different loglikehood.(-14018 and -14407). Is it because the random seed? When I test this alignment on other softwares I can always got same results(about -14018). 
The attachments are the log file. Both are from the PTHREADS version but got very different loglikehood.
Thanks.
[dna.raxml.log](https://github.com/amkozlov/raxml-ng/files/2491714/dna.raxml.log)
[dna1.raxml.log](https://github.com/amkozlov/raxml-ng/files/2491715/dna1.raxml.log)

**Comment by amkozlov** [comment]
Hi,
so I doubled-checked and it's simply an effect of different random seeds (and thus distinct starting trees) - and has nothing to do with PTHREADS vs. MPI version.This is expected behavior, and actually quite common on datasets with relatively few sites and thus weaker signal. It is therefore highly recommended to use multiple starting trees, e.g. `--tree pars{10},rand{10}`.

Hope this helps,
Alexey

**Comment by cynthiawqy** [comment]
Hi Alexey,

Thanks for your reply!
