### ISSUE TITLE
unrecognized option '--search1'

### ISSUE THREAD

**Issue by lsuhpchelp** [amkozlov/raxml-ng#55]
v0.7.0 beta
[cbro117@mike019 ng-tutorial]$ raxml-ng-mpi --search1 --msa prim.phy --model GTR+G --prefix T5 --threads 2 --seed 2
raxml-ng-mpi: unrecognized option '--search1'
Other tests work so far. 
The installation seems ok, except "Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)". Not sure if this is related to the "unrecognized option '--search1'"

**Comment by amkozlov** [comment]
Sorry for confusion, for the tutorial you need the latest RAxML-NG version from the dev branch. v0.7.0 does not have the `--search1 ` command (in fact, `--search` in v0.7.0 corresponds to `--search1` in v0.7.0dev, since I changed the default number of starting trees). I added corresponding warning to the tutorial.

`Could NOT find GTest` error has nothing to do with `--search1`, and as long as you don't need to run unit test, you can safely ignore it.

**Comment by amkozlov** [comment]
you're welcome :)
