### ISSUE TITLE
Comprehensive tree as a toplogical constraint

### ISSUE THREAD

**Issue by pyspider** [amkozlov/raxml-ng#81]
Hi，
  I am trying to infer a phylogenetic tree from a trimmed alignment. And I want to use a previous tree as a topological constraint (--tree-constraint/-g) that was generated from full matrix. I encountered this error when I used a comprehensive tree as a topological constraint on raxml-ng.
`ERROR: You provided a comprehensive, fully-resolved tree as a topological constraint.
Since this is almost certainly not what you intended, RAxML-NG will now exit...`
  However, It seems that raxml can work using same constraint tree. 
`raxmlHPC-HYBRID -T 4 -n mitochondrial_result -s infile.txt -m GTRGAMMA -p 12345 -g constraint.tre -f a -N 1000 -x 12345 --asc-corr lewis`
  I am not sure whether raxml-ng doesn't allow to use a comprehensive tree. But raxml can use this constraint tree.  Does I can use a comprehensive tree from full matrix as a topological constraint tree to infer a new phylogenetic tree using a reduced subset of full matrix on raxml/raxml-ng?

**Comment by amkozlov** [comment]
Well if your constraint tree is comprehensive (=contains all taxa) and fully-resolved (=binary), there is no sense to perform tree search since there is one single topology which satisfies the constraint (=constraint tree itself). That's why RAxML-NG exits with error.

If your goal is to optimize branch lengths and model parameters on the trimmed alignment, please use `--evaluate` command instead.

**Comment by amkozlov** [comment]
I consider this one solved -> closing.
